---
- name: Prometheus
  hosts: prometheus
  roles:
    - prometheus.prometheus.prometheus
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- name: Install alertmanager
  hosts: alertmanager
  roles:
    - prometheus.prometheus.alertmanager
  tags:
    - alertmanager

- name: Install Blackbox
  hosts: blackbox_exporter
  roles:
    - prometheus.prometheus.blackbox_exporter
  tags:
    - blackbox_exporter
