prometheus_scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - "127.0.0.1:{{ prometheus_port }}"

  - job_name: alertmanager
    metrics_path: /metrics
    static_configs:
      - targets:
        - "{{ alertmanager_web_listen_address }}"

  - job_name: federation
    metrics_path: /federate
    honor_labels: true
    scheme: https
    params:
      match[]:
        - '{__name__=~"substrate.*"}'
    file_sd_configs:
      - files:
        - "{{ prometheus_config_dir }}/file_sd/members.yml"
    relabel_configs:
    - source_labels: [__address__]
      regex: '^.*(dwellir\.com)$'
      target_label: __metrics_path__
      replacement: "/{{ dwellir_api_key }}/federate"