prometheus_version: 2.45.3

prometheus_port: 9090
prometheus_web_listen_address: "127.0.0.1:{{ prometheus_port }}"

prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

prometheus_storage_retention: "365d"